/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";

interface ReviewSession {
  title: string;
  location: string;
  rsvpLink: string;
  expired: boolean;
  date: string;
  academicConsultant: string;
}

interface ReviewSessionsProps {
  globalData: {
    reviewSessions: ReviewSession[];
  };
}

export default function ReviewSessions({ globalData }: ReviewSessionsProps) {
  const [sessions, setSessions] = useState<ReviewSession[]>([]);

  useEffect(() => {
    setSessions(globalData.reviewSessions);
  }, [globalData.reviewSessions]);

  return (
    <>
      <Head>
        <title>Review Sessions | Commerce Mentorship Program</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="left-0 right-0 top-0 h-32 w-full overflow-hidden">
        <img
          src="/banner.png"
          alt="ubc banner"
          className="h-auto w-full object-center"
        />
      </div>
      <main className="flex min-h-[600px] flex-col items-start justify-start  bg-white">
        <div className="container mx-auto max-w-[1440px] flex-grow p-4">
          <h1 className="mb-4 text-3xl font-bold ">REVIEW SESSIONS</h1>
          <p className="mb-4 text-base">
            Here you can find a collection of past review packages, sorted based
            on year, classes, and finals/midterms.
          </p>
          <p className="mb-8 text-base">
            Last updated: <b>October 26th, 2023</b>
          </p>

          {sessions?.map((session, index) => (
            <div
              key={index}
              className="container mb-8 flex flex-col items-start justify-start gap-6 rounded-lg bg-white px-6 py-8 shadow-md"
            >
              <h2 className="text-2xl font-bold">{session.title}</h2>
              <div className="flex w-full flex-col justify-between space-y-4 sm:flex-row sm:items-center">
                <div className="flex flex-col">
                  <div className="mb-2 flex items-center">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      viewBox="0 0 24 24"
                      fill="currentColor"
                      className="h-8 w-8"
                    >
                      <path d="M11.7 2.805a.75.75 0 01.6 0A60.65 60.65 0 0122.83 8.72a.75.75 0 01-.231 1.337 49.949 49.949 0 00-9.902 3.912l-.003.002-.34.18a.75.75 0 01-.707 0A50.009 50.009 0 007.5 12.174v-.224c0-.131.067-.248.172-.311a54.614 54.614 0 014.653-2.52.75.75 0 00-.65-1.352 56.129 56.129 0 00-4.78 2.589 1.858 1.858 0 00-.859 1.228 49.803 49.803 0 00-4.634-1.527.75.75 0 01-.231-1.337A60.653 60.653 0 0111.7 2.805z" />
                      <path d="M13.06 15.473a48.45 48.45 0 017.666-3.282c.134 1.414.22 2.843.255 4.285a.75.75 0 01-.46.71 47.878 47.878 0 00-8.105 4.342.75.75 0 01-.832 0 47.877 47.877 0 00-8.104-4.342.75.75 0 01-.461-.71c.035-1.442.121-2.87.255-4.286A48.4 48.4 0 016 13.18v1.27a1.5 1.5 0 00-.14 2.508c-.09.38-.222.753-.397 1.11.452.213.901.434 1.346.661a6.729 6.729 0 00.551-1.608 1.5 1.5 0 00.14-2.67v-.645a48.549 48.549 0 013.44 1.668 2.25 2.25 0 002.12 0z" />
                      <path d="M4.462 19.462c.42-.419.753-.89 1-1.394.453.213.902.434 1.347.661a6.743 6.743 0 01-1.286 1.794.75.75 0 11-1.06-1.06z" />
                    </svg>

                    <span className="ml-2 font-bold">
                      {session.academicConsultant}
                    </span>
                  </div>

                  <div className="mb-2 flex items-center">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      viewBox="0 0 24 24"
                      fill="currentColor"
                      className="h-8 w-8"
                    >
                      <path d="M12.75 12.75a.75.75 0 11-1.5 0 .75.75 0 011.5 0zM7.5 15.75a.75.75 0 100-1.5.75.75 0 000 1.5zM8.25 17.25a.75.75 0 11-1.5 0 .75.75 0 011.5 0zM9.75 15.75a.75.75 0 100-1.5.75.75 0 000 1.5zM10.5 17.25a.75.75 0 11-1.5 0 .75.75 0 011.5 0zM12 15.75a.75.75 0 100-1.5.75.75 0 000 1.5zM12.75 17.25a.75.75 0 11-1.5 0 .75.75 0 011.5 0zM14.25 15.75a.75.75 0 100-1.5.75.75 0 000 1.5zM15 17.25a.75.75 0 11-1.5 0 .75.75 0 011.5 0zM16.5 15.75a.75.75 0 100-1.5.75.75 0 000 1.5zM15 12.75a.75.75 0 11-1.5 0 .75.75 0 011.5 0zM16.5 13.5a.75.75 0 100-1.5.75.75 0 000 1.5z" />
                      <path d="M6.75 2.25A.75.75 0 017.5 3v1.5h9V3A.75.75 0 0118 3v1.5h.75a3 3 0 013 3v11.25a3 3 0 01-3 3H5.25a3 3 0 01-3-3V7.5a3 3 0 013-3H6V3a.75.75 0 01.75-.75zm13.5 9a1.5 1.5 0 00-1.5-1.5H5.25a1.5 1.5 0 00-1.5 1.5v7.5a1.5 1.5 0 001.5 1.5h13.5a1.5 1.5 0 001.5-1.5v-7.5z" />
                    </svg>

                    <span className="ml-2 font-bold">{session.date}</span>
                  </div>
                  <div className="flex items-center">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      viewBox="0 0 24 24"
                      fill="currentColor"
                      className="h-8 w-8"
                    >
                      <path d="M11.54 22.351l.07.04.028.016a.76.76 0 00.723 0l.028-.015.071-.041a16.975 16.975 0 001.144-.742 19.58 19.58 0 002.683-2.282c1.944-1.99 3.963-4.98 3.963-8.827a8.25 8.25 0 00-16.5 0c0 3.846 2.02 6.837 3.963 8.827a19.58 19.58 0 002.682 2.282 16.975 16.975 0 001.145.742zM12 13.5a3 3 0 100-6 3 3 0 000 6z" />
                    </svg>
                    <span className="ml-2 font-bold">{session.location}</span>
                  </div>
                </div>
                <Link href={session.rsvpLink}>
                  <button className="whitespace-nowrap rounded-lg bg-orange-600 px-4 py-2 font-semibold text-white transition duration-300 hover:bg-black">
                    RSVP Here
                  </button>
                </Link>
              </div>
            </div>
          ))}

          <Link href="/contact">
            <p className="text-base underline">
              Can&apos;t find what you&apos;re looking for?
            </p>
          </Link>
        </div>
      </main>
    </>
  );
}
